In [ ]:
# DataCo Supply Chain Data Cleaning

## Purpose

# This notebook prepares the raw DataCo datasets for downstream SQL analysis, statistical analysis, and Power BI reporting.

# Cleaning decisions are based on the profiling notebook, data dictionary, and business relevance.

# Raw datasets are not modified directly. Cleaned copies are created and exported for later phases.

In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_csv(r"..\data\DataCoSupplyChainDataset.csv" , encoding = "latin1")
dictionary = pd.read_csv(r"..\data\DescriptionDataCoSupplyChain.csv" , encoding = "latin1")
clickstream = pd.read_csv(r"..\data\Tokenized_access_logs.csv" , encoding = "latin1")

In [3]:
orders_clean = orders.copy()
clickstream_clean = clickstream.copy()

## Cleaning Principle

# The original raw datasets are preserved unchanged. All cleaning operations are applied only to copied DataFrames.

In [4]:
print("orders shape : " , orders_clean.shape)
print("dictionary shape : " , dictionary.shape)
print("clickstream shape : " , clickstream_clean.shape)

orders shape :  (180519, 53)
dictionary shape :  (52, 2)
clickstream shape :  (469977, 8)

In [5]:
# Data Type Cleaning

## Objective

# Convert columns to their appropriate data types based on the data dictionary and business meaning.

# No values are modified during this step. Only data types are corrected to enable accurate analysis and calculations.

In [6]:
orders_clean.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [7]:
orders_clean.select_dtypes(include = "object").columns.tolist()

['Type',
 'Delivery Status',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Department Name',
 'Market',
 'Order City',
 'Order Country',
 'order date (DateOrders)',
 'Order Region',
 'Order State',
 'Order Status',
 'Product Image',
 'Product Name',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [8]:
orders_clean.select_dtypes(include = "number").columns.tolist()

['Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Late_delivery_risk',
 'Category Id',
 'Customer Id',
 'Customer Zipcode',
 'Department Id',
 'Latitude',
 'Longitude',
 'Order Customer Id',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Price',
 'Product Status']

In [ ]:
# Observation:

# The dataset currently contains both numeric and object-type columns. Some object columns represent dates and will require conversion to datetime format.

In [22]:
date_columns = [
    'order date (DateOrders)',
     'shipping date (DateOrders)'
]

for col in date_columns:
    orders_clean[col] = pd.to_datetime(
        orders_clean[col] ,
        errors = "coerce"
    )

In [31]:
orders_clean[date_columns].dtypes

# Data Type Cleaning

## Reason

# The Data Profiling notebook identified that the order and shipping date columns were stored as text (`object`) 
# despite representing temporal information.

# To support time-series analysis, delivery calculations, SQL date functions, and Power BI date hierarchies, 
# these fields are converted to the appropriate datetime data type.

# No other columns required datatype correction based on the profiling investigation.

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [ ]:
# Remove Personally Identifiable Information (PII)

## Reason

# Based on the findings from the **Data Profiling** notebook, the following columns contain personally identifiable information (PII)
# and provide no analytical value for supply chain, sales, logistics, or customer segmentation.

# Removing these fields improves data privacy while reducing unnecessary attributes in the analytical dataset.

In [38]:
pii_columns = [
    "Customer Email",
    "Customer Fname",
    "Customer Lname",
    "Customer Password",
    "Customer Street"
]


for col in pii_columns:
    print(f"{col}: {col in orders.columns}")

Customer Email: True
Customer Fname: True
Customer Lname: True
Customer Password: True
Customer Street: True

In [41]:
missing_from_clean = set(orders.columns) - set(orders_clean.columns)
print(sorted(missing_from_clean))

['Customer Email', 'Customer Fname', 'Customer Lname', 'Customer Password', 'Customer Street']

In [42]:
orders_clean.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id',
       'Product Category Id', 'Product Description', 'Product Image',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [ ]:
## Cleaning Decision

# Based on the findings from the Data Profiling notebook, personally identifiable information (PII) columns have been removed from the analytical dataset to protect customer privacy and reduce unnecessary attributes.

# This transformation has already been applied to the working dataset.

In [ ]:
# Remove Low Business Value Columns

## Reason

# The Data Profiling notebook identified certain columns as having limited analytical usefulness for business intelligence, SQL reporting, and dashboard development.

# These columns either contain excessive missing values or provide descriptive information that is not required for downstream analytical tasks.

# Removing these attributes simplifies the analytical dataset while preserving all business-critical information.

In [43]:
low_value_columns = [
    "Product Description"
]

orders_clean.drop(
    columns=low_value_columns,
    inplace=True
)

In [44]:
orders_clean.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id',
       'Product Category Id', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [ ]:
# Standardize Text Values

## Reason

# The profiling investigation identified inconsistencies in whitespace and text formatting across several categorical attributes.

# Standardizing text values improves grouping accuracy, SQL joins, filtering operations, and dashboard consistency without altering the underlying business meaning.

In [45]:
text_columns = orders_clean.select_dtypes(include = "object").columns

for column in text_columns:
    orders_clean[column] = (
        orders_clean[column]
        .str.strip()
    )

In [46]:
orders_clean[text_columns].head()

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Segment,Customer State,Department Name,Market,Order City,Order Country,Order Region,Order State,Order Status,Product Image,Product Name,Shipping Mode
0,DEBIT,Advance shipping,Sporting Goods,Caguas,Puerto Rico,Consumer,PR,Fitness,Pacific Asia,Bekasi,Indonesia,Southeast Asia,Java Occidental,COMPLETE,http://images.acmesports.sports/Smart+watch,Smart watch,Standard Class
1,TRANSFER,Late delivery,Sporting Goods,Caguas,Puerto Rico,Consumer,PR,Fitness,Pacific Asia,Bikaner,India,South Asia,Rajastán,PENDING,http://images.acmesports.sports/Smart+watch,Smart watch,Standard Class
2,CASH,Shipping on time,Sporting Goods,San Jose,EE. UU.,Consumer,CA,Fitness,Pacific Asia,Bikaner,India,South Asia,Rajastán,CLOSED,http://images.acmesports.sports/Smart+watch,Smart watch,Standard Class
3,DEBIT,Advance shipping,Sporting Goods,Los Angeles,EE. UU.,Home Office,CA,Fitness,Pacific Asia,Townsville,Australia,Oceania,Queensland,COMPLETE,http://images.acmesports.sports/Smart+watch,Smart watch,Standard Class
4,PAYMENT,Advance shipping,Sporting Goods,Caguas,Puerto Rico,Corporate,PR,Fitness,Pacific Asia,Townsville,Australia,Oceania,Queensland,PENDING_PAYMENT,http://images.acmesports.sports/Smart+watch,Smart watch,Standard Class

In [ ]:
# Feature Engineering

## Reason

# Following datatype conversion, additional temporal attributes are derived from the order date.

# These features improve downstream SQL queries, statistical analysis, and Power BI visualizations by enabling monthly, quarterly, yearly, and weekday-based reporting.

In [47]:
orders_clean["Order Year"] = orders_clean["order date (DateOrders)"].dt.year
orders_clean["Order Month"] = orders_clean["order date (DateOrders)"].dt.month
orders_clean["Order Quarter"] = orders_clean["order date (DateOrders)"].dt.quarter
orders_clean["Order Weekday"] = orders_clean["order date (DateOrders)"].dt.day_name()

In [48]:
orders_clean[
    [
        "order date (DateOrders)",
        "Order Year",
        "Order Month",
        "Order Quarter",
        "Order Weekday"
    ]
].head()

,order date (DateOrders),Order Year,Order Month,Order Quarter,Order Weekday
0,2018-01-31 22:56:00,2018,1,1,Wednesday
1,2018-01-13 12:27:00,2018,1,1,Saturday
2,2018-01-13 12:06:00,2018,1,1,Saturday
3,2018-01-13 11:45:00,2018,1,1,Saturday
4,2018-01-13 11:24:00,2018,1,1,Saturday

In [ ]:
# Final Validation

## Reason

# The cleaned dataset is validated to ensure that all transformations have been successfully applied without compromising the dataset's structure or analytical readiness.

# This validation confirms that the dataset is prepared for PostgreSQL loading, SQL analysis, statistical investigation, and Power BI reporting.

In [49]:
orders_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Id                    180519 non-null  int64
 12  Customer Segment               180519 non-null  object
 13  Customer State                 180519 non-null  object
 14  Customer Zipcode               180516 non-null  float64
 15  Department Id                  180519 non-null  int64
 16  Department Name                180519 non-null  object
 17  Latitude                       180519 non-null  float64
 18  Longitude                      180519 non-null  float64
 19  Market                         180519 non-null  object
 20  Order City                     180519 non-null  object
 21  Order Country                  180519 non-null  object
 22  Order Customer Id              180519 non-null  int64
 23  order date (DateOrders)        180519 non-null  datetime64[ns]
 24  Order Id                       180519 non-null  int64
 25  Order Item Cardprod Id         180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Id                  180519 non-null  int64
 29  Order Item Product Price       180519 non-null  float64
 30  Order Item Profit Ratio        180519 non-null  float64
 31  Order Item Quantity            180519 non-null  int64
 32  Sales                          180519 non-null  float64
 33  Order Item Total               180519 non-null  float64
 34  Order Profit Per Order         180519 non-null  float64
 35  Order Region                   180519 non-null  object
 36  Order State                    180519 non-null  object
 37  Order Status                   180519 non-null  object
 38  Order Zipcode                  24840 non-null   float64
 39  Product Card Id                180519 non-null  int64
 40  Product Category Id            180519 non-null  int64
 41  Product Image                  180519 non-null  object
 42  Product Name                   180519 non-null  object
 43  Product Price                  180519 non-null  float64
 44  Product Status                 180519 non-null  int64
 45  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 46  Shipping Mode                  180519 non-null  object
 47  Order Year                     180519 non-null  int32
 48  Order Month                    180519 non-null  int32
 49  Order Quarter                  180519 non-null  int32
 50  Order Weekday                  180519 non-null  object
dtypes: datetime64[ns](2), float64(14), int32(3), int64(14), object(18)
memory usage: 68.2+ MB

In [50]:
orders_clean.shape

(180519, 51)

In [51]:
orders_clean.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,Order Year,Order Month,Order Quarter,Order Weekday
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class,2018,1,1,Wednesday
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class,2018,1,1,Saturday
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class,2018,1,1,Saturday
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class,2018,1,1,Saturday
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,2018,1,1,Saturday

In [52]:
orders_clean.columns = (
    orders_clean.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("(", "", regex=False)
        .str.replace(")", "", regex=False)
)

In [53]:
orders_clean.columns

Index(['type', 'days_for_shipping_real', 'days_for_shipment_scheduled',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_id', 'category_name', 'customer_city',
       'customer_country', 'customer_id', 'customer_segment', 'customer_state',
       'customer_zipcode', 'department_id', 'department_name', 'latitude',
       'longitude', 'market', 'order_city', 'order_country',
       'order_customer_id', 'order_date_dateorders', 'order_id',
       'order_item_cardprod_id', 'order_item_discount',
       'order_item_discount_rate', 'order_item_id', 'order_item_product_price',
       'order_item_profit_ratio', 'order_item_quantity', 'sales',
       'order_item_total', 'order_profit_per_order', 'order_region',
       'order_state', 'order_status', 'order_zipcode', 'product_card_id',
       'product_category_id', 'product_image', 'product_name', 'product_price',
       'product_status', 'shipping_date_dateorders', 'shipping_mode',
       'order_year', 'order_month', 'order_quarter', 'order_weekday'],
      dtype='object')

In [ ]:
# Business Rule Cleaning

## Cleaning Decision

# Business rule validation performed during profiling identified values requiring verification before analytical use.

# Only values violating logical business rules are corrected or removed.

In [55]:
orders_clean = orders_clean[
    orders_clean["order_item_quantity"] > 0
]

In [58]:
orders_clean = orders_clean[
    orders_clean["product_price"] >= 0
]

In [59]:
orders_clean.drop_duplicates(inplace=True)

In [ ]:
## Cleaning Decision

# Based on profiling findings, Product Description contained limited analytical value and significant missing values.

# The column was removed.

# Customer Zipcode missing values were retained because geographic analysis remains possible using Country and City.

In [61]:
orders_clean.to_csv(
    "../data/clean/orders_clean.csv",
    index=False
)

In [62]:
clickstream_clean.to_csv(
    "../data/clean/clickstream_clean.csv",
    index=False
)

In [ ]:
# Cleaning Summary

## Overview

# The cleaning process transformed the raw operational dataset into an analytics-ready dataset suitable for PostgreSQL, SQL analysis, statistical investigation, and Power BI reporting.

# All cleaning decisions were implemented based on findings documented in the **Data Profiling** notebook. No transformation was performed without prior investigation and business justification.

## Transformations Performed

# -  Converted the **Order Date** and **Shipping Date** columns from text (`object`) to `datetime` format to support temporal analysis and date-based reporting.

# -  Removed **Personally Identifiable Information (PII)** columns, including customer email, name, password, and street address, to improve data privacy and eliminate non-analytical attributes.

# -  Removed columns identified during profiling as having **low analytical value** or limited business relevance for downstream reporting.

# -  Standardized text values by removing unnecessary leading and trailing whitespace to improve consistency across categorical fields.

# -  Applied cleaning decisions based on business rules established during the profiling phase while preserving records that represent valid business transactions.

# -  Preserved legitimate business duplicates where multiple records represent different products within the same customer order.

# -  Retained business-relevant missing values where removal or imputation could negatively affect analytical integrity.

# -  Created additional temporal features, including **Order Year**, **Order Month**, **Order Quarter**, and **Order Weekday**, to support SQL queries, statistical analysis, and dashboard development.

# -  Validated the cleaned dataset to ensure structural consistency, correct data types, and readiness for downstream analytical workflows.

# -  Exported the cleaned datasets for PostgreSQL loading and subsequent analysis.

## Final Outcome

# The cleaned datasets are structured, documented, and ready for the next stages of the project, including PostgreSQL database integration, SQL querying, statistical analysis, Power BI dashboard development, and executive business reporting.

In [4]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\pallav\anaconda3\lib\site-packages (2.0.43)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: greenlet>=1 in c:\users\pallav\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pallav\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------------------- -------------------- 1.3/2.8 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 17.3 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [8]:
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql+psycopg2://postgres:PASS@localhost:YOURS/dataco_supply_chain"
)
orders_clean.to_sql(
    name="orders_clean",
    schema="analytics",
    con=engine,
    if_exists="replace",
    index=False
)

31